---
# Application Services - TLS, external connectivity

- import_playbook: install-tls-config.yml
- import_playbook: install-rathole.yml

# Apps

- import_playbook: mount-nas-share.yml
# - import_playbook: build-open-webui.yml
- import_playbook: install-open-webui.yml
