---
- import_playbook: setup-local-facts.yml
- import_playbook: setup-base-compute.yml
- import_playbook: configure-netplan.yml
- import_playbook: install-vault-pass-setup.yml
- import_playbook: install-ycluster-package.yml
- import_playbook: setup-base-infrastructure.yml
- import_playbook: setup-linux-boot.yml
- import_playbook: setup-admin-user.yml
- import_playbook: install-dhcp-leader-election.yml
- import_playbook: setup-network-services.yml
- import_playbook: setup-pxe-boot.yml
- import_playbook: install-certbot.yml
- import_playbook: setup-web-services.yml
- import_playbook: setup-secrets-volume.yml
- import_playbook: setup-tang.yml
- import_playbook: enable-serial-console.yml
- import_playbook: install-amtterm.yml
- import_playbook: install-docker-official.yml
# - import_playbook: install-meshcommander.yml
- import_playbook: install-rocm.yml
- import_playbook: install-llama-cpp-rocm.yml
